site_name: StreamMUSE Documentation
site_description: Documentation for StreamMUSE project
site_author: StreamMUSE Team
site_url: https://streammuse.github.io/docs

# Repository
repo_name: StreamMUSE/docs
repo_url: https://github.com/StreamMUSE/docs

# Theme configuration
theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

# Navigation
nav:
  - 首页: index.md
  - Real-Time Inference System:
    - 概述: real-time-inference/index.md
    - 快速开始: real-time-inference/quickstart.md
    - 参数指南: real-time-inference/parameter.md
    - 系统架构: real-time-inference/architecture.md
    - 配置指南: real-time-inference/configuration.md
    - API 参考: real-time-inference/api-reference.md
    - 性能优化: real-time-inference/performance.md
    - 故障排除: real-time-inference/troubleshooting.md
  - Training Framework:
    - 概述: training-framework/index.md
    - 框架设计: training-framework/design.md
    - 环境设置: training-framework/setup.md
    - 数据准备: training-framework/data-preparation.md
    - 模型训练: training-framework/model-training.md
    - 实验管理: training-framework/experiment-management.md
    - 部署指南: training-framework/deployment.md
  - 常见问题: faq.md
  - 更新日志: changelog.md

# Plugins
plugins:
  - search:
      lang: 
        - en
        - zh
  - git-revision-date-localized:
      type: date
