site_name: StreamMUSE Documentation
site_description: Documentation for StreamMUSE project
site_author: StreamMUSE Team
site_url: https://streammuse.github.io/docs

# Repository
repo_name: StreamMUSE/docs
repo_url: https://github.com/StreamMUSE/docs

# Theme configuration
theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

# Navigation
nav:
  - 首页: index.md
  - Real-Time Inference System:
    - 概述: real-time-inference/index.md
    - 快速开始: real-time-inference/quickstart.md
    - 参数指南: real-time-inference/parameter.md
    - 系统架构: real-time-inference/architecture.md
    - 配置指南: real-time-inference/configuration.md
    - API 参考: real-time-inference/api-reference.md
    - 性能优化: real-time-inference/performance.md
    - 故障排除: real-time-inference/troubleshooting.md
  - Training Framework:
    - 概述: training-framework/index_zh.md
    - 快速开始: training-framework/quickstart_zh.md
    - 项目规范: training-framework/project-structure_zh.md
    - 模块文档:
      - 模块概览: training-framework/modules/index_zh.md
      - 核心模块:
        - 模型模块: training-framework/modules/model/README_zh.md
        - 网络模块: training-framework/modules/network/README_zh.md
        - 数据集模块: training-framework/modules/dataset/README_zh.md
      - 工具模块:
        - 回调模块: training-framework/modules/callback/README_zh.md
        - 数据模块: training-framework/modules/datamodule/README_zh.md
        - 日志器模块: training-framework/modules/logger/README_zh.md
        - 学习率调度器模块: training-framework/modules/lr_scheduler/README_zh.md
        - 优化器模块: training-framework/modules/optimizer/README_zh.md
        - 训练器模块: training-framework/modules/trainer/README_zh.md
        - 工具模块: training-framework/modules/utils/README_zh.md
        - 项目模块: training-framework/modules/project/README_zh.md
        - 指标模块: training-framework/modules/metric/README_zh.md
  - 常见问题: faq.md
  - 更新日志: changelog.md

# Plugins
plugins:
  - search:
      lang: 
        - en
        - zh
  - git-revision-date-localized:
      type: date
